version: '3.2'

services:
  sensors:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: vessels_db
      PGDATABASETEST: vessels_db_test
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
      
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5433:5433"
    volumes:
      - ./data/:/var/lib/postgresql/data/:z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
